# shellcheck shell=bash
# Harness + backend registry. See docs/SANDBOX-PLAN.md §17.
#
# Sourced from TWO places, deliberately:
#   * the host CLI (./sandbox)          — validate flags, know which egress domains a
#                                         harness/backend needs, pick default models;
#   * inside the workload (sandbox-harness) — install, configure and launch the agent.
# So: bash-only, no side effects on source, no host-only or container-only assumptions.
#
# A harness file (harnesses/<name>.sh) defines:
#   H_NAME H_BIN H_DESC H_DOMAINS
#   H_HOME       state dir, relative to $HOME — only meaningful inside the workload
#   H_HOME_ENV   compose variable that binds the shared host home onto H_HOME
#   H_HOST_HOME  that home's directory name under $SANDBOX_HOMES on the host
#   H_SKILLS     where this harness discovers SKILL.md skills (all four share the format)
#   h_install()    build-time install (runs in the image build, network = host)
#   h_configure()  container-side: write provider config, emit KEY=VALUE env on stdout
#   h_launch()     container-side: set H_CMD=(...) — argv used to start the agent
# A backend file (backends/<name>.sh) defines:
#   B_NAME B_URL B_OPENAI_URL B_ANTHROPIC_URL B_ANTHROPIC_COMPAT B_API B_KEY B_DOMAINS
# and honours SANDBOX_LLM_URL / SANDBOX_LLM_API_KEY overrides.

HARNESS_LIST="claudecode pi omp prime-agent"
BACKEND_LIST="anthropic ollama openai-compat"
HARNESS_DEFAULT="${SANDBOX_HARNESS:-claudecode}"
BACKEND_DEFAULT="${SANDBOX_LLM_BACKEND:-anthropic}"

HARNESS_LIB_DIR="${HARNESS_LIB_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# The host CLI defines its own die(); provide one when sourced standalone.
type die >/dev/null 2>&1 || die() { echo "sandbox-harness: $*" >&2; exit 1; }

in_list() { case " $2 " in *" $1 "*) return 0;; esac; return 1; }
harness_known() { in_list "$1" "$HARNESS_LIST"; }
backend_known() { in_list "$1" "$BACKEND_LIST"; }

harness_load() {
  harness_known "$1" || die "unknown harness '$1' (known: $HARNESS_LIST)"
  # shellcheck source=/dev/null
  . "$HARNESS_LIB_DIR/harnesses/$1.sh"
}
backend_load() {
  backend_known "$1" || die "unknown llm backend '$1' (known: $BACKEND_LIST)"
  # shellcheck source=/dev/null
  . "$HARNESS_LIB_DIR/backends/$1.sh"
}

# Hostname out of a URL — what the egress allowlist wants (no scheme, no port/path).
url_host() { local u="${1#*://}"; u="${u%%/*}"; u="${u%%\?*}"; echo "${u%%:*}"; }

# Colons are meaningful to the pi-family model selectors (`--model sonnet:high` means
# "thinking level high"), and Ollama ids are full of them (`gemma4:31b`). Every generated
# provider entry therefore carries a colon-free `name`, and that is what we select by.
model_alias() { echo "$1" | tr ':/' '--'; }

# Sets PROVIDER_ARGS to the --model/--context arguments for the selected models.
# Shared by every pi-family harness so they cannot drift apart.
set_provider_model_args() {
  PROVIDER_ARGS=()
  if [ -n "${SANDBOX_MODEL:-}" ]; then
    PROVIDER_ARGS+=(--model "$SANDBOX_MODEL")
    if [ -n "${SANDBOX_MODEL_CONTEXT:-}" ]; then
      PROVIDER_ARGS+=(--context "$SANDBOX_MODEL=$SANDBOX_MODEL_CONTEXT")
    fi
  fi
  if [ -n "${SANDBOX_SMALL_MODEL:-}" ] && [ "${SANDBOX_SMALL_MODEL:-}" != "${SANDBOX_MODEL:-}" ]; then
    PROVIDER_ARGS+=(--model "$SANDBOX_SMALL_MODEL")
    if [ -n "${SANDBOX_SMALL_MODEL_CONTEXT:-}" ]; then
      PROVIDER_ARGS+=(--context "$SANDBOX_SMALL_MODEL=$SANDBOX_SMALL_MODEL_CONTEXT")
    fi
  fi
  return 0
}

# --- web search -------------------------------------------------------------
# All four harnesses read the same SKILL.md convention (Claude Code's, adopted by pi, omp
# and prime-agent), so ONE generated skill teaches every one of them that the `websearch`
# command exists. Without it the command is on PATH but the model has no reason to try it.
SKILL_MARKER="<!-- generated by the sandbox CLI — regenerated on launch, safe to delete -->"

sync_websearch_skill() {  # SKILLS_DIR
  local dir="$1" skill="$1/websearch" file="$1/websearch/SKILL.md"
  [ -n "$dir" ] || return 0
  if [ -z "${SANDBOX_SEARCH_URL:-}" ]; then
    # Search is off: withdraw OUR skill so the model is not told about a command that
    # will only error. A hand-written skill of the same name is left alone.
    if [ -f "$file" ] && grep -qF "$SKILL_MARKER" "$file"; then rm -rf "$skill"; fi
    return 0
  fi
  # The Claude home symlinks skills/ at a read-only mount (Minions) — don't fight it.
  if [ -L "$dir" ]; then
    echo "sandbox-harness: $dir is a symlink (read-only skills) — skipping the websearch skill;" >&2
    echo "sandbox-harness: the 'websearch' command is still on PATH." >&2
    return 0
  fi
  mkdir -p "$skill" 2>/dev/null || { echo "sandbox-harness: cannot write $skill — skipping websearch skill" >&2; return 0; }
  cat > "$file" <<EOF
---
name: websearch
description: Search the web for current information — docs, error messages, releases, CVEs, anything past the model's training cutoff. Use whenever the answer depends on something recent or external rather than on this repository.
---

$SKILL_MARKER

# Web search

This sandbox has a search endpoint reachable with the \`websearch\` command:

\`\`\`bash
websearch how to configure searxng json api      # top 8 results
websearch -n 3 rust tokio select macro           # fewer results
websearch --category news kubernetes cve         # a specific category
websearch --json openssl 3.5 release             # machine-readable
\`\`\`

Each result is a title, a URL and a snippet.

**Reading a result page is a separate, deliberate step.** Egress from this sandbox is
deny-by-default, so fetching a linked URL fails unless its domain is on the allowlist.
Do not try to work around that — if a page is genuinely needed, say which domain you
need and the operator can add it with \`./sandbox allow --url <domain>\`. Snippets are
often enough; prefer refining the query over asking for a fetch.
EOF
  return 0
}

# Write a pi-family provider block (pi / omp / prime-agent share this schema).
# Usage: write_provider_config FILE json|yaml PROVIDER BASE_URL API KEY MODEL_ARGS...
write_provider_config() {
  local file="$1" fmt="$2" provider="$3" base="$4" api="$5" key="$6"; shift 6
  mkdir -p "$(dirname "$file")"
  python3 "$HARNESS_LIB_DIR/models_config.py" \
    --file "$file" --format "$fmt" --provider "$provider" \
    --base-url "$base" --api "$api" --api-key "$key" "$@"
}
