#!/usr/bin/env python3
"""Render a provider block into a pi-family harness's model config.

pi, omp and prime-agent all read the same shape — a `providers` map of
{baseUrl, api, apiKey, models[]} — pi and prime-agent as JSON (~/.pi/agent/models.json,
~/.prime/agent/models.json), omp as YAML (~/.omp/agent/models.yml). This writes it for
whichever of the three was selected. See docs/SANDBOX-PLAN.md §17.

Ownership rule: a config we generated carries a sidecar marker (`<file>.sandbox-generated`)
and we rewrite our own provider key in place, leaving every other provider the user added
untouched. A config we did NOT generate is never clobbered — it is moved aside to
`<file>.pre-sandbox` (once; an existing backup is never overwritten) and the user is told.

No YAML library is required: the emitted document is a fixed, flat shape with quoted
scalars, so it is written directly. Stdlib only — this runs inside the workload.
"""

import argparse
import json
import os
import sys

MARKER_SUFFIX = ".sandbox-generated"
MARKER_TEXT = (
    "Written by the sandbox CLI (`sandbox open --harness ... --llm-backend ...`).\n"
    "The provider block it manages is regenerated on every launch; other providers\n"
    "in the file are preserved. Delete this marker to take the file over yourself.\n"
)


def model_alias(model_id):
    """Colon-free display name.

    `--model gemma4:31b` is ambiguous to the pi-family selectors, where a colon means a
    thinking level (`--model sonnet:high`). Every entry therefore gets a name we can
    select by unambiguously, while `id` keeps the exact string the API expects.
    """
    return model_id.replace(":", "-").replace("/", "-")


def build_provider(args):
    # ID=TOKENS pairs: the model's real context window. Without it the harness assumes
    # its own default (128k), which either truncates a big local model or overruns a
    # small one mid-session.
    windows = {}
    for pair in args.context:
        model_id, _, tokens = pair.partition("=")
        if tokens.isdigit():
            windows[model_id] = int(tokens)

    # ID=text,image pairs: what the model can be SENT. Without this the pi family assumes
    # text-only and disables anything vision-dependent (omp's snapcompact summariser is
    # the one that says so out loud) even against a multimodal model.
    inputs = {}
    for pair in args.input:
        model_id, _, mods = pair.partition("=")
        mods = [m for m in mods.split(",") if m]
        if mods:
            inputs[model_id] = mods

    seen, models = set(), []
    for m in args.model:
        if m in seen:
            continue
        seen.add(m)
        entry = {"id": m, "name": model_alias(m)}
        if m in windows:
            entry["contextWindow"] = windows[m]
        if m in inputs:
            entry["input"] = inputs[m]
        models.append(entry)
    provider = {"baseUrl": args.base_url, "api": args.api, "models": models}
    if args.api_key:
        provider["apiKey"] = args.api_key
    return provider


def yaml_dump(config):
    """Emit the fixed providers-map shape as YAML (flat, all scalars quoted)."""
    out = ["# Generated by the sandbox CLI — see <file>.sandbox-generated.", "providers:"]
    for name, provider in config["providers"].items():
        out.append(f"  {json.dumps(name)}:")
        for key in ("baseUrl", "api", "apiKey"):
            if key in provider:
                out.append(f"    {key}: {json.dumps(provider[key])}")
        out.append("    models:")
        for model in provider["models"]:
            out.append(f"      - id: {json.dumps(model['id'])}")
            out.append(f"        name: {json.dumps(model['name'])}")
            if "contextWindow" in model:
                out.append(f"        contextWindow: {model['contextWindow']}")
            if "input" in model:
                # JSON list == YAML flow sequence, so this needs no extra quoting rules.
                out.append(f"        input: {json.dumps(model['input'])}")
    return "\n".join(out) + "\n"


def load_existing(path, fmt, marker):
    """Existing config we may merge into, or {} — moving a foreign file aside first."""
    if not os.path.exists(path):
        return {}
    if not os.path.exists(marker):
        backup = path + ".pre-sandbox"
        if not os.path.exists(backup):
            os.rename(path, backup)
            print(f"sandbox-harness: kept your existing config at {backup}", file=sys.stderr)
        else:
            print(
                f"sandbox-harness: {path} is not ours and {backup} already exists — "
                "overwriting the live file",
                file=sys.stderr,
            )
        return {}
    if fmt != "json":
        return {}  # YAML we own is regenerated wholesale (no parser in the workload)
    try:
        with open(path) as fh:
            data = json.load(fh)
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError) as exc:
        print(f"sandbox-harness: ignoring unreadable {path} ({exc})", file=sys.stderr)
        return {}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", required=True)
    ap.add_argument("--format", choices=("json", "yaml"), required=True)
    ap.add_argument("--provider", required=True)
    ap.add_argument("--base-url", required=True)
    ap.add_argument("--api", required=True)
    ap.add_argument("--api-key", default="")
    ap.add_argument("--model", action="append", default=[])
    ap.add_argument("--context", action="append", default=[], metavar="ID=TOKENS")
    ap.add_argument("--input", action="append", default=[], metavar="ID=text,image")
    args = ap.parse_args()

    if not args.model:
        sys.exit("sandbox-harness: at least one --model is required")

    marker = args.file + MARKER_SUFFIX
    config = load_existing(args.file, args.format, marker)
    config.setdefault("providers", {})[args.provider] = build_provider(args)

    os.makedirs(os.path.dirname(args.file) or ".", exist_ok=True)
    text = json.dumps(config, indent=2) + "\n" if args.format == "json" else yaml_dump(config)
    tmp = args.file + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(text)
    os.replace(tmp, args.file)  # atomic: a crash mid-write never leaves a half-config
    with open(marker, "w") as fh:
        fh.write(MARKER_TEXT)
    print(f"sandbox-harness: wrote provider '{args.provider}' -> {args.file}", file=sys.stderr)


if __name__ == "__main__":
    main()
